import * as jestPlugin from "serverless-jest-plugin";
import * as mod from "./../handler";
// tests for getAllProducts
// Generated by serverless-jest-plugin

const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: "catalogBatchProcess" });

const snsInstance = {
  publish: jest.fn(),
};

jest.mock("aws-sdk", () => {
  return { SNS: jest.fn(() => snsInstance) };
});

// @ts-ignore
const fakeEvent = {
  Records: [
    {
      body: JSON.stringify({
        count: 12,
        description: "Test Short Product Description",
        price: 15,
        title: "Product ##4",
      }),
    },
  ],
};

describe("catalogBatchProcess.test", () => {
  beforeAll((done) => {
    done();
  });

  it("should run", () => {
    return wrapped.run({}).then((res) => {
      expect(res).toBeDefined();
    });
  });

  it("should contain correct statusCode", () => {
    return wrapped.run({Records: []}).then((res) => {
        expect(res.statusCode).toEqual(202);
    });
  });
});
