import * as jestPlugin from 'serverless-jest-plugin';
import * as mod from './../handler';
// tests for getAllProducts
// Generated by serverless-jest-plugin

const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'getAllProducts' });

type Response = {
  statusCode: number;
  body: string;
}

describe('getAllProducts', () => {
  beforeAll((done) => {
//  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it('implement tests here', () => {
    return wrapped.run({}).then((response: Response) => {
      expect(response).toBeDefined();
    });
  });

  it('should contain body', () => {
    return wrapped.run({}).then((response: Response) => {
      expect(response.body).toBeDefined()
    });
  });

  it('should contain body result', () => {
    return wrapped.run({}).then((response: Response) => {
      const body = JSON.parse(response.body);

      expect(body).toBeDefined()
    });
  });

  it('should contain correct code', () => {
    return wrapped.run({}).then((response: Response) => {
      expect(response.statusCode).toEqual(500);
    });
  });

});
