import * as jestPlugin from "serverless-jest-plugin";

import * as mod from "./../handler";

// tests for getAllProducts
// Generated by serverless-jest-plugin

const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: "getProductById" });

describe("getProductById.test", () => {
  beforeAll((done) => {
    done();
  });

  it("implement tests here", () => {
    return wrapped.run({}).then((response) => {
      expect(response).toBeDefined();
    });
  });
});
