swagger: "2.0"
info:
  description: "AWS RS-school #3"
  version: "1.0.0"
  title: "Swagger products"

  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "7d9p5khj1a.execute-api.eu-west-1.amazonaws.com"
basePath: "/"
tags:
- name: "products"
  description: "Everything about your products"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "https"
paths:
 /dev/products:
    get:
      tags:
      - "products"
      summary: "Returns all product"
      description: "Returns all product"
      operationId: "getAllProduct"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: object
            properties:
              code: 
                type: string
                enum:
                  - "success"
                  - "error"
              result:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: "#/definitions/Product"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Product not found"
          
 /dev/products/{productId}:
    get:
      tags:
      - "products"
      summary: "Find product by ID"
      description: "Returns a single product"
      operationId: "getProductById"
      produces:
      - "application/json"
      parameters:
      - name: "productId"
        in: "path"
        description: "ID of product to return"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Product"
        "400":
          description: "Invalid ID supplied"
          
definitions:
  Product:
    type: "object"
    properties:
      price:
        type: "integer"
        format: "int64"
      count:
        type: "integer"
        format: "int64"
      id:
        type: "string"
        format: "guid"
      title:
        type: "string"
        description: "product title"
      imageName:
        type: "string"
        description: "image name"
      description:
        type: "string"
        description: "product description" 
