---
swagger: "2.0"
info:
  version: "2020-11-16T16:34:54Z"
  title: "dev-rsschool-import-service"
host: "jkzgfse086.execute-api.eu-west-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /import:
    get:
      parameters:
      - name: "name"
        in: "query"
        required: true
        type: "string"
      responses: {}
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
