
name: CI Node.js AWS BE

on: [push]

jobs:
###############################
  bff-service:
    name: bff-service-feels-fine
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: bff-service
    strategy:
      fail-fast: true
      matrix:
        node-version: [12.x]
        
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2

      - name: install dependencies
        run: npm i

      - name: sls packing
        run: npm run pack

      - name: run tests
        run: npm run test
###############################
  import-service:
    name: import-service-feels-fine
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: import-service
    strategy:
      fail-fast: true
      matrix:
        node-version: [12.x]
        
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2

      - name: install dependencies
        run: npm i

      - name: sls packing
        run: npm run pack

      - name: run tests
        run: npm run test
###############################
  product-service:
    name: product-service-feels-fine
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: product-service
    strategy:
      fail-fast: true
      matrix:
        node-version: [12.x]
        
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2

      - name: install dependencies
        run: npm i

      - name: sls packing
        run: npm run pack

      - name: run tests
        run: npm run test
###############################
  auth-service:
    name: auth-service-feels-fine
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: authorization-service
    strategy:
      fail-fast: true
      matrix:
        node-version: [12.x]
        
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2

      - name: install dependencies
        run: npm i

      - name: sls packing
        run: npm run pack

      - name: run tests
        run: npm run test
